### ISSUE TITLE
[Bug]: excluded_apps.txt always installed

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/WAU-MSI#24]
### The problem

Installing with `LISTPATH=SomePath`
**excluded_apps.txt** always gets created and is not overwritten when **WAU** is run beacause the locally newly installed file is newer.
Should we change the `Test-ListPath.ps1` to **always** download an external list or the MSI installation to take in account that the list is gonna be downloaded and not install a local list?

### What version of WAU has the issue?

This

### What version of winget are you using?

current

**Comment by Romanitho** [comment]
Good point. Need to be determined.

**Comment by Romanitho** [comment]
I think we should not onboard excluded list by default. Because on each update, it will reinstall the default list...

**Comment by KnifMelti** [comment]
File in Component;
![image](https://github.com/user-attachments/assets/c888bc84-27db-4d58-84c2-4aab9264348c)

Component Permanent/Never overwrite:
![image](https://github.com/user-attachments/assets/feda39d2-c7de-4333-af8b-e4aa4f50d92b)

![image](https://github.com/user-attachments/assets/93fcc47b-bb18-43e2-b4e3-bff2ec3ae9fe)

**Comment by Romanitho** [comment]
We should handle the list differently. A "default_excluded_apps.txt" that is overrided by any excluded or included_apps.txt. this way, in case the default one change on the github repo, excluded or included remain the one chosen by admin.

**Comment by Romanitho** [comment]
https://github.com/Romanitho/WAU-MSI/releases/tag/v1.23.12
now we have a solid version

**Comment by KnifMelti** [comment]
Nice!
Everyting works...
...upgrade from the old WAU, upgrade to the newest .14 WAU-MSI, List handling, Uninstall

When uninstalling the old WAU, you could also use `conhost.exe --headless` in the process `Start-Process cmd.exe -ArgumentList "/c $($OldWAUConfig.UninstallString)" -Wait`

**Comment by Romanitho** [comment]
i wanted to keep the uninstall of old WAU visible. I think if your run WAU MSI as system, ti should not display anything. Not tried yet.
i'm currently fixing the "repair" msi function, as it didn't remove the list if you repair WAU without providing list (for instance to get back to default one)

**Comment by Romanitho** [comment]
I finally got it working 😮‍💨 install, uninstall, repair... work good. List also.
https://github.com/Romanitho/WAU-MSI/releases/tag/v1.23.19

**Comment by Romanitho** [comment]
Should be fixed now 😅
