### ISSUE TITLE
[Bug]: WAU_ModsPath gets deleted

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/WAU-MSI#50]
### The problem

Old WAU installed and already run.
Installing WAU-MSI 1.23.28 with:
`LISTPATH=https://www.knifmelti.se/wau/lists MODPATH=https://www.knifmelti.se/wau/mods USERCONTEXT=1 UPDATESATLOGON=0 UPDATESINTERVAL=Daily DONOTRUNONMETERED=0 STARTMENUSHORTCUT=1 DESKTOPSHORTCUT=1 /qn`
Everyting is OK and it gets installed with all correct values, uninstalling the old WAU.
Running WAU-MSI it detects version 1.23.29 and updates.
After that the data of the value `WAU_ModsPath` is deleted, everything else is correct:
![image](https://github.com/user-attachments/assets/e7c2ae18-3bd8-4ebb-80fd-3ead6631ef38)

### What version of WAU has the issue?

WAU-MSI

### What version of Windows are you using (ex. Windows 11 22H2)?

current

### What version of winget are you using?

current

**Comment by KnifMelti** [comment]
It also shows the cmd window when uninstalling the old WAU, poising a security risk running in system context (Properties menu, links starting browser)

**Comment by Romanitho** [comment]
thanks. I'll have a look to the setting that vanishes, and will hide WAU uninstall.

**Comment by KnifMelti** [comment]
You could also hide the VC-redist with `/quiet` instead of `/passive`

**Comment by Romanitho** [comment]
/passive was there to see things on this beta. Of course, now we can run /quiet as it is not visible anyway

**Comment by KnifMelti** [comment]
It is visible running under servicui/ system

**Comment by Romanitho** [comment]
Oh yes. I'm lost with all my tests ahah

**Comment by Romanitho** [comment]
and I forgot an "S" in MODPATH.

**Comment by Romanitho** [comment]
Ok, I think a space was the culprit

**Comment by Romanitho** [comment]
all seems good now. tested on WSB. Thanks a lot for your tests and reports ❤️

**Comment by KnifMelti** [comment]
Everything is perfect!
And the slow installation of prereqs is gone under WSB (must have been something in the cloud)!

Noticed that the MSI-upgrade from one version to another is showing the MSI-install, but it also shows the notif and the result of the upgrade, so that is maybe not an issue (but I can imagine users reacting to the sudden MSI-dialog popping up in the middle of the screen ontop resulting in calls to ServiceDesk...)

**Comment by Romanitho** [comment]
Maybe the slow was due to the progresspreference option missing ?!
Regarding the wau msi upgrade with /passive option was set for troubleshoot. We can, of course, change it to /qn, and everything will be good.
And maybe in a close future, wau will be in the whitelist and no autoupdate will be necessary anymore 😅🤣

**Comment by Romanitho** [comment]
Next in the (my) pipe, change wix v3 to wix v4 or 5...

**Comment by KnifMelti** [comment]
GPO handling maybe?

**Comment by KnifMelti** [comment]
> maybe in a close future, wau will be in the whitelist and no autoupdate will be necessary anymore

What came first, the egg or the hen?

**Comment by KnifMelti** [comment]
> Rework that part a bit ?

No. I just noticed it's missing in the registry (if I'm not wrong)...

**Comment by Romanitho** [comment]
Really? I haven't tested it yet. I would have thought there wouldn't be a problem.

**Comment by KnifMelti** [comment]
I haven't tested. But the trigger isn't there via properties/registry:
`if ($WAUConfig.WAU_RunGPOManagement -eq 1)`

**Comment by KnifMelti** [comment]
Ah, I see...
#_**Add**_ (or update) tag to activate WAU-Policies Management

**Comment by Romanitho** [comment]
For me, shortcuts should not be manageable through GPO now. It is configurable on first install. I mean, in general, this is something that is handle on first install, no ?

So I was thinking about a potential decommission of shortcuts wia GPO.

The second thing that often confuse my customers is the "Activate WAU GPO Management". They ask me, why should I have to enable something, to enable something else 😅
By default, when a GPO is set, it configures the setting without the need of an on-top GPO.

**Comment by KnifMelti** [comment]
Yup

**Comment by Romanitho** [comment]
Yes. And also ListPath should be GPO by default if a list is declared in GPO.

**Comment by KnifMelti** [comment]
How are you planning this transform from the old installer to this MSI-based installer?
Do you plan to implement all changes here in https://github.com/Romanitho/Winget-AutoUpdate (not losing Forks/Stars/Discussions etc.)?
Is it time for me to fork this repo and help you (thinking of ADMX at the moment)?

**Comment by Romanitho** [comment]
I was thinking to pass to version 2.x.x because of course there are big chances... and it's a new start :)
You can fork and add your changes here, to continue tests etc... and we will reproduces the same changes to current repo when we are happy with this new version. OR, I can simply create a new branch and you can push your changes over there. But, i'm open to any suggestions if you have good ideas :)

**Comment by Romanitho** [comment]
In the next days, I'll start to bring things to this branch https://github.com/Romanitho/Winget-AutoUpdate/tree/v2-msi

**Comment by Romanitho** [comment]
+
I will probably rewrite the way we manage WAU self-updates, cause I don't want to push MSI on current installed WAU. But I want to be able to continue to push hotfixes to current ones to support v1 a bit longer.
